baseURL = "https://docs.mjcb.io/"
title = "docs.mjcb.io"
theme = "hugo-geekdoc"

pluralizeListTitles = false
pygmentsUseClasses = true
pygmentsCodeFences = true
disablePathToLower = true
enableGitInfo = true
enableRobotsTXT = true

googleAnalytics = "G-TC72E9W5TV"

[markup]
    [markup.goldmark.renderer]
    unsafe = true

    [markup.tableOfContents]
    startLevel = 1
    endLevel = 9

[taxonomies]
    tag = "tags"

[params]
    ga_analytics = "G-TC72E9W5TV"

    # (Optional, default 6) Set how many table of contents levels to be showed on page.
    # Use false to hide ToC, note that 0 will default to 6 (https://gohugo.io/functions/default/)
    # You can also specify this parameter per page in front matter.
    geekdocToC = 6

    # (Optional, default false) Render menu from data file in 'data/menu/main.yaml'.
    # See also https://geekdocs.de/usage/menus/#bundle-menu.
    geekdocMenuBundle = false

    # (Optional, default false) Collapse all menu entries, can not be overwritten
    # per page if enabled. Can be enabled per page via 'geekdocCollapseSection'.
    geekdocCollapseAllSections = false

    # (Optional, default true) Show page navigation links at the bottom of each
    # docs page (bundle menu only).
    geekdocNextPrev = false

    # (Optional, default true) Show a breadcrumb navigation bar at the top of each docs page.
    # You can also specify this parameter per page in front matter.
    geekdocBreadcrumb = true

    # (Optional, default none) Set source repository location. Used for 'Edit page' links.
    # You can also specify this parameter per page in front matter.
    geekdocRepo = "https://github.com/matthew-tfs/docs.mjcb.io"

    # (Optional, default none) Enable 'Edit page' links. Requires 'GeekdocRepo' param
    # and the path must point to the parent directory of the 'content' folder.
    # You can also specify this parameter per page in front matter.
    geekdocEditPath = "edit/main"

    # (Optional, default true) Enables search function with flexsearch.
    # Index is built on the fly and might slow down your website.
    geekdocSearch = true

    # (Optional, default false) Display search results with the parent folder as prefix. This
    # option allows you to distinguish between files with the same name in different folders.
    # NOTE: This parameter only applies when 'geekdocSearch = true'.
    geekdocSearchShowParent = true

    # (Optional, default none) Add a link to your Legal Notice page to the site footer.
    # It can be either a remote url or a local file path relative to your content directory.
    #geekdocLegalNotice = "https://blog.example.com/legal"

    # (Optional, default none) Add a link to your Privacy Policy page to the site footer.
    # It can be either a remote url or a local file path relative to your content directory.
    geekdocPrivacyPolicy = "/privacy-policy"

    # (Optional, default true) Add an anchor link to headlines.
    geekdocAnchor = true

    # (Optional, default true) Copy anchor url to clipboard on click.
    geekdocAnchorCopy = true

    # (Optional, default true) Enable or disable image lazy loading for images rendered
    # by the 'img' shortcode.
    geekdocImageLazyLoading = true

    # (Optional, default false) Set HTMl <base> to .Site.BaseURL if enabled. It might be required
    # if a subdirectory is used within Hugos BaseURL.
    # See https://developer.mozilla.org/de/docs/Web/HTML/Element/base.
    geekdocOverwriteHTMLBase = false

    # (Optional, default false) Auto-decrease brightness of images and add a slightly grayscale to avoid
    # bright spots while using the dark mode.
    geekdocDarkModeDim = false

    # (Optional, default false) Enforce code blocks to always use the dark color theme.
    geekdocDarkModeCode = false

    # (Optional, default true) Display a "Back to top" link in the site footer.
    geekdocBackToTop = true

    # (Optional, default false) Enable or disable adding tags for post pages automatically to the navigation sidebar.
    geekdocTagsToMenu = true

    # (Optional, default 'title') Configure how to sort file-tree menu entries. Possible options are 'title', 'linktitle',
    # 'date', 'publishdate', 'expirydate' or 'lastmod'. Every option can be used with a reverse modifier as well
    # e.g. 'title_reverse'.
    geekdocFileTreeSortBy = "title"

    # (Optional, default none) Adds a "Content licensed under <license>" line to the footer.
    # Could be used if you want to define a default license for your content.
    [params.geekdocContentLicense]
        name = "MIT"
        link = "https://opensource.org/licenses/MIT"
